version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.8
      - image: contribsys/faktory:0.9.6

    working_directory: ~/repo
    steps:
      - checkout

      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix do deps.get, compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix test
